### PR TITLE
Shift optimization

### PR DESCRIPTION
**Pull request by andreysobol**
micro optimization
thanks @miladpiri

### CODE REVIEW

**Review by miladpiri — APPROVED** [review]

**Review by vladbochok — APPROVED** [review]

**Comment by ly0va** [comment]
I'm not sure this optimizes anything. The cost of the shift operation does not depend on its arguments, or is it not about that?

**Comment by vladbochok** [comment]
> I'm not sure this optimizes anything. The cost of the shift operation does not depend on its arguments, or is it not about that?

Optimization really works. There are actually two tricks going on here:
- for shift use variables of type (`uint256`, `uint256`), not (`uint256`, `uint8`)
- declare a `currentIndex` variable before a loop

**Comment by andreysobol** [comment]
> I'm not sure this optimizes anything. The cost of the shift operation does not depend on its arguments, or is it not about that?

i tested it

```
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.7.0 <0.9.0;

contract Playground {
    
    function t1() public {
        uint iters = 100;
        uint currentIndex = 342;
        for (uint i=0; i<iters; i++) { 
            currentIndex = currentIndex >> 1;
        }
    }

    function t2() public {
        uint iters = 100;
        uint origin = 342;
        for (uint i=0; i<iters; i++) { 
            uint currentIndex = origin >> i;
        }
    }

}
```

result - 41344 and 40866

so we can save 478 gas

or 4.78 per one iteration

so if merkle tree depth will be 10 (realisitic amount) we will save 47 gas

it's 0.000279 or 0.0279% of all gas spending for "add" operation lol

**Review by barakshani — APPROVED** [review]

**Comment by ly0va** [comment]
> 0.0279% of all gas spending for "add" operation

I believe if the optimization is so negligible, it's more important to preserve code readability and reduce cognitive complexity. Which I think it does not. Do we really need it?

**Comment by vladbochok** [comment]
> > 0.0279% of all gas spending for "add" operation
> 
> I believe if the optimization is so negligible, it's more important to preserve code readability and reduce cognitive complexity. Which I think it does not. Do we really need it?

IMHO, readability of the code has not suffered

**Comment by andreysobol** [comment]
> > > 0.0279% of all gas spending for "add" operation
> > 
> > 
> > I believe if the optimization is so negligible, it's more important to preserve code readability and reduce cognitive complexity. Which I think it does not. Do we really need it?
> 
> IMHO, readability of the code has not suffered

i agree there is no so many differences in understandability between `>> level` and `>> 1`

**Review by ly0va — APPROVED** [review]

**Review by Barichek — APPROVED** [review]

**Pull request merged**
